greeting: Hello

endpoints:
  health:
    sensitive: false

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

---

spring:
  profiles: spanish

greeting: Hola